# Generated by Django 4.0.6 on 2022-07-26 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='parking',
            name='check_start_date',
        ),
        migrations.AlterField(
            model_name='parking',
            name='cost',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
