# Generated by Django 4.0.5 on 2022-06-30 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_brand_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='model',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
