# Generated by Django 4.0.5 on 2022-06-30 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_brand_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='park',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
