# Generated by Django 4.0.5 on 2022-06-30 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_park_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='park',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
