# Generated by Django 4.0.5 on 2022-07-01 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_permission_permission_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='reservation_type',
            field=models.CharField(choices=[('One Time', 'One Time'), ('Daily', 'Daily'), ('Weekly', 'Weekly')], max_length=100),
        ),
    ]
