# Generated by Django 4.0.5 on 2022-07-01 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_reservation_reservation_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='reserved_period',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
