# Generated by Django 4.0.5 on 2022-07-01 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_reservation_options_alter_car_weight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carparking',
            name='cost',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='history',
            name='total_payments',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='cost',
            field=models.IntegerField(),
        ),
    ]
