# Generated by Django 4.0.5 on 2022-07-01 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_carparking_cost_alter_history_total_payments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='reserved_period',
            field=models.DurationField(),
        ),
    ]
