# Generated by Django 4.0.5 on 2022-07-01 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_reservation_reserved_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='reserved_period',
            field=models.FloatField(),
        ),
    ]
