# Generated by Django 4.0.6 on 2022-07-11 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_reservation_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='park',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.park'),
        ),
    ]
